### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by garry191091** [icon-project/icon-sdk-js#10]
I am integrating it with CDN in  browser, but when i import `import IconService from 'icon-sdk-js';`

i am getting error in console `Uncaught SyntaxError: Cannot use import statement outside a module`.

what can be the solution of it.

**Comment by sanghoocon** [comment]
Only if I know where the import statement used, I can tell you solution.
At a glance it seems that there is a bundling issue.

But, If you use the CDN, global window object has the property of 'icon-sdk-js'.
So, you can use the IconService like this, `const IconService = window['icon-sdk-js']`, not using import statement.
I hope it helps :)

**Comment by Spl3en** [comment]
How did you import your js ? Did you use `<script type="module" src="..."></script>` (don't forget the type module)

**Comment by garry191091** [comment]
Hello,

I did exactly the same thing as my code below.  I have included  `thetype="module"` in the script

`<script type="module" src="https://cdn.jsdelivr.net/gh/icon-project/icon-sdk-js@latest/build/icon-sdk-js.web.min.js"></script>
<script type="text/javascript">
    const IconService = window['icon-sdk-js'] ; 
</script>>`

Error:- 
`Uncaught TypeError: Cannot set property 'icon-sdk-js' of undefined`

Also did use import statement, but the same error,

**Comment by sanghoocon** [comment]
To set the property 'icon-sdk-js' on global window, remove the `type="module"`.
