### ISSUE TITLE
[FORMAT ERROR] Confirmed transaction object is invalid.

### ISSUE THREAD

**Issue by skchang0710** [icon-project/icon-sdk-js#11]
It seems there is unparsable response data while calling getLastBlock()

Error : [FORMAT ERROR] Confirmed transaction object is invalid.

Following is the API response from https://wallet.icon.foundation/api/v3
`{
  "jsonrpc": "2.0",
  "result": {
    "version": "0.3",
    "height": 11246361,
    "signature": "2Wev8Bb8yUohf6KOc6Dcu4d6gN9WA93UTg1UrwRmELAvdPSMtkp+b/t4F2ZH9qDrAtJ9hh5I47IfeUx8xI4fAQA=",
    "prev_block_hash": "7704b8814526e2b53ee82111ccaaa538485a2891b0cd568e03ffec8b6292977d",
    "merkle_tree_root_hash": "d3503227cbdeb52f837c35fe53469ce8b8c9c7f80673e7df170b409dc09753cb",
    "time_stamp": 1574247539731290,
    "confirmed_transaction_list": [
      {
        "version": "0x3",
        "timestamp": "0x597c51164eb5a",
        "dataType": "base",
        "data": {
          "prep": {
            "irep": "0xa4b66e7ed77bb7af02e",
            "rrep": "0x28d",
            "totalDelegation": "0x985a505c48dee931ec01bb",
            "value": "0x3ff3c31951799a25"
          },
          "result": {
            "coveredByFee": "0x1977cdc0897000",
            "coveredByOverIssuedICX": "0x0",
            "issue": "0x3fda4b4b90f02a25"
          }
        },
        "txHash": "0xde1d38ce3db8ddbf3b17caa4c9bf1ffd42fca0f1e40fa9c3ae65307e3aa31a2f"
      },
      {
        "data": {
          "method": "transfer",
          "params": {
            "_value": "0x56bc75e2d63100000",
            "_to": "hxd87067f60b7f89c30fb9a9fc95dbd2dafcd9ea38"
          }
        },
        "stepLimit": "0x7a120",
        "signature": "WcYKLQCaUDCz+HfpU1RpVjAPJu5ziy0zAWWh+jWns7s5LZgmEDV6UQjDSEFk3VlGAkGNdqqb5x4LjJ1AbVLQpgE=",
        "dataType": "call",
        "nid": "0x1",
        "from": "hx01ef2d50c35a518366fa03df8b201cf7ac95ef40",
        "to": "cx429731644462ebcfd22185df38727273f16f9b87",
        "version": "0x3",
        "nonce": "0xf4240",
        "timestamp": "0x597c51155f230",
        "txHash": "0x11e84a9027a1d459c0342ed8e3984414265ecee0fc1ca97cee46471fb052bb49"
      }
    ],
    "block_hash": "dc53b1dc747169122c708c089f49e1ca876906368e6d077fbd015e7f257f6c84",
    "peer_id": "hx554ea6c0c56e6f30682dcaa79a326da3a364899f",
    "next_leader": "hx554ea6c0c56e6f30682dcaa79a326da3a364899f"
  },
  "id": 1234
}
`

**Comment by couldseeme** [comment]
Hello, thank you for reporting the issue.
As we updated our package to support the JSON-RPC API v3 specification, this issue will be resolved in the new version of 'icon-sdk-js'(v0.0.18). Please try it and ask us if there are any problems. Thank you.
