### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by roccomuso** [icon-project/icon-sdk-js#14]
Any reason why LICENSE is Apache-2.0?

Switching to MIT would allow easy spreading and adoption.

**Comment by sink772** [comment]
MIT and Apache licenses are basically same thing and they both essentially say "do whatever you want with this, just don’t sue me.", while the Apache license uses more words which might help in a dispute.

https://exygy.com/blog/which-license-should-i-use-mit-vs-apache-vs-gpl/

So I don't think using the Apache license prevents easy spreading and adoption.

**Comment by sink772** [comment]
It seems you don't have any objection to my opinion. Closing the issue.
