### ISSUE TITLE
Fee handling question

### ISSUE THREAD

**Issue by roccomuso** [icon-project/icon-sdk-js#17]
Looking at the code I didn't get how Fees are handled and computed in ICON when sending a tx.
Can someone explain?

**Comment by BadAppsDevelopment** [comment]
I could be wrong but I think it is calculated using SCORE. The developer portal breaks it down based on the number of steps * the going rate of the coin. 

Dev Portal: 
https://www.icondev.io/docs/step-estimation

**Comment by roccomuso** [comment]
So you just provide a `stepLimit` and the fee is deducted from your address balance?

**Comment by BadAppsDevelopment** [comment]
For a simple transaction, you wouldn't need to calculating the step limit. You could just an SDK that handles all of that for you. 

The step limit is the number of steps on T-Bears to complete the transaction. The step limit is the conversion is referenced in a video on the docs page, think it was 1:1000 or something close to that.

**Comment by roccomuso** [comment]
- I don't wanna rely on the SDK, I need to understand if the `stepLimit` for normal transactions can be like a constant, without any server API call.
- So the conversion is fixed. (`Initial setup: 1 ICX = 100,000,000 Step`)

**Comment by BadAppsDevelopment** [comment]
It looks like transactions are only completed once sent to the T-Bears network. Which is where the transaction fee comes from (activity on T-Bear). Requiring the use of an SDK to interact with the network.

**Comment by roccomuso** [comment]
What do you mean with "completed"? validated? added to the blockchain?
The T-Bears network is the Icon mainnet?
The question is, can I use a fixed `stepLimit` for normal txs between EOA?
Or do I need to get limit (or estimation) from the network?

**Comment by BadAppsDevelopment** [comment]
simple answer, no you can not use a fixed ```steplimit``` for a transaction. You need an estimate from the network. 
At least from my understanding of reading the docs.

**Comment by roccomuso** [comment]
So, If I put a `stepLimit`, the tx fee is gonna be <= to that limit? but this could leave dust in the wallet

**Comment by BadAppsDevelopment** [comment]
That's how it looks, you can even use the API to return the transaction fee for the specified address.

**Comment by roccomuso** [comment]
what do you mean? which API?

**Comment by BadAppsDevelopment** [comment]
the javascript API includes a function call under the 
```
const IconService = require('icon-sdk-js');

/*  HttpProvider is used to communicate with http.
    In this example, we use Yeouido node as provider. */
const provider = new IconService.HttpProvider('https://bicon.net.solidwallet.io/api/v3');

/* Create IconService instance */
const iconService = new IconService(provider);

const apiList = iconService.getScoreApi('cx0000000000000000000000000000000000000001').execute().then(apiList => {
    console.log(apiList.getMethod('getStepCosts'))
});
```

**Comment by Spl3en** [comment]
> I don't wanna rely on the SDK, I need to understand if the stepLimit for normal transactions can be like a constant, without any server API call.

The "stepLimit" variable is a governance variable, that may be changed in the future.
However, it hasn't changed since the launch of mainnet, and it isn't planned soon to change it.

So, the simple answer is you can *assume* the stepLimit is a constant.
However, the complicated answer is you need to query the SCORE cx0000000000000000000000000000000000000001 to retrieve the step cost for an ICX transaction (with no data : stepCost = defaultCost * StepPrice => 100000 * 10000000000 = 1000000000000000 loops = 0.001 ICX)
You can use the code mentionned by @BadAppsDevelopment above for that.

You can review all these governance variables here : 
https://tracker.icon.foundation/contract/cx0000000000000000000000000000000000000001#readcontract

**Comment by roccomuso** [comment]
Ok thanks for the explanation. So right now the fee is `0.001 ICX` but might change in the future.

**Comment by Spl3en** [comment]
I recently wrote the JS function for calling the debug_estimateStep, as it isn't supported by the current version of the ICON SDK JS. Here it is :

```
    __estimateCallStep(from, to, method, value, params = {}) {
        const transaction = {
            "jsonrpc": "2.0",
            "method": "debug_estimateStep",
            "id": 1,
            "params": {
                "version": "0x3",
                "from": from,
                "to": to,
                "value": IconService.IconConverter.toHex(IconService.IconConverter.toBigNumber(value)),
                "timestamp": IconService.IconConverter.toHex((new Date()).getTime() * 1000),
                "nid": IconService.IconConverter.toHex(IconService.IconConverter.toBigNumber(this._nid)),
                "nonce": "0x1",
                "dataType": "call",
                "data": {
                    "method": method,
                    "params": params
                }
            }
        }

        return new Promise((resolve, reject) => {
            try {
                const result = this._iconDebugService.provider.request(transaction).execute()
                resolve(result)
            } catch (err) {
                reject(err)
            }
        })
    }
```

```this._nid``` is the Network ID (see https://www.icondev.io/v0.8/docs/icon-networks)
```this._iconDebugService``` is an instance of the iconService pointing to the debug endpoint : 

```
const httpDebugProvider = new IconService.HttpProvider(url + '/api/debug/v3')
this._iconDebugService = new IconService(httpDebugProvider)
```

Hope that helps anyone else looking for estimate steps with JS.

**Comment by roccomuso** [comment]
Is this debug method reliable?

I tried to call it trying to put as amount `10 ICX` and it returned `100000` as stepLimit. But networks fail to accept txs with such low fee.

**Comment by duyphanz** [comment]
I have a look at how Hana wallet calculated Fee estimation, and here is what I figured out:

First, they get `stepPrice` by making a request to https://berlin.net.solidwallet.io/api/v3

```json
{
  "jsonrpc": "2.0",
  "id": 1652537128704,
  "method": "icx_call",
  "params": {
    "to": "cx0000000000000000000000000000000000000001",
    "dataType": "call",
    "data": {
      "method": "getStepPrice"
    }
  }
}
```
Then, they get `estimateStep` by making a request to https://berlin.net.solidwallet.io/api/v3d, the difference is that they uses the `v3d` version compared with the first request.

```json
{
  "jsonrpc": "2.0",
  "method": "debug_estimateStep",
  "params": {
   ...
  },
  "id": 1652537128399
}
```

The `fee estimation =  stepPrice * estimateStep`

--------------------------

About how to turn on Hana wallet debug page:

- Go to extension page and click on `Background page`

<img width="368" alt="image" src="https://user-images.githubusercontent.com/13731780/168429774-8f490e32-dea9-4a92-baf6-732b8406b42f.png">


- Observe on Network tab

<img width="608" alt="image" src="https://user-images.githubusercontent.com/13731780/168429809-8cf6429c-9a03-443d-af85-56ef15898b29.png">

Hope this help!
