### ISSUE TITLE
API to get a list of transactions

### ISSUE THREAD

**Issue by roccomuso** [icon-project/icon-sdk-js#18]
Is there an API to get the list of transactions (in/out) given an Address?

**Comment by Spl3en** [comment]
No, there is no such thing.

You can use the ICON tracker API though - please note that it is not an official endpoint and may change without warning.

https://tracker.icon.foundation/v3/address/txList?page=1&count=25&address=hx6e265205099e984dc7f027fa6664043bd1f06278

**Comment by roccomuso** [comment]
Is the tracker open source? can I spawn my own tracker instance?

**Comment by Spl3en** [comment]
> Is the tracker open source? can I spawn my own tracker instance?

Easy easy : no, and no.

Complicated answer : 
It is not published as open source officially.
However, you can get a docker instance of the tracker here : 
https://hub.docker.com/r/iconloop/docker_tracker
So you can decompile the .jar and retrieve the tracker source code that way. But there is no documentation.
About spawning your own instance, it's hard to make it work as it depends on multiple components.

**Comment by roccomuso** [comment]
So how wallets are supposed to list the tx without relying on a single point of failure (the public tracker instance)?

**Comment by Spl3en** [comment]
You can run your own citizen node and rebuild the transaction history from that.
