### ISSUE TITLE
Need utility function for validating address

### ISSUE THREAD

**Issue by octocat512** [icon-project/icon-sdk-js#21]

**Comment by ICONationTeam** [comment]
Agreed.

We use the following code if that may help : 

```js
export const isICONAddress = function (address) {
  return /^(hx|cx)?[0-9a-f]{40}$/i.test(address)
}
export const isICONAddressContract = function (address) {
  return /^(cx)?[0-9a-f]{40}$/i.test(address)
}
export const isICONAddressEOA = function (address) {
  return /^(hx)?[0-9a-f]{40}$/i.test(address)
}

```

**Comment by ICONationTeam** [comment]
Actually I just noticed there's already one implemented : 

https://github.com/icon-project/icon-sdk-js/blob/3ab30c0dbc2759cb480942b8463044fd0c89a703/lib/data/Validator.js#L77

- Validator.isAddress
- Validator.isEoaAddress
- Validator.isScoreAddress

https://github.com/icon-project/icon-sdk-js/blob/3ab30c0dbc2759cb480942b8463044fd0c89a703/lib/data/Validator.js#L77
