### ISSUE TITLE
Need Typescript Types Support

### ISSUE THREAD

**Issue by octocat512** [icon-project/icon-sdk-js#22]

**Comment by bkbooth** [comment]
Hey @WeiLi512, I've just ran into this issue. I might look at what's involved in getting the types added to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped). I'd be interested to get some feedback from you if I do, or if you've made a start then I'd be happy to collaborate on that

**Comment by WeiLi512** [comment]
I am very happy to give feedback if you do that. I am using the icon-sdk-js library in one project that uses typescript.

**Comment by WeiLi512** [comment]
I will also involve in your project if you start the project.

**Comment by WeiLi512** [comment]
Hey @bkbooth, Did you start the development of adding types? I want to contribute to the project. Please let me know if you have any updates. Thanks.

**Comment by bkbooth** [comment]
@WeiLi512 I've sort of made a start. I have an`@types/icon-sdk-js.d.ts` local to my current project where I'm trying to type things from the SDK as I use them. I might take a look today how to move that to a separate repo so we can collaborate.

**Comment by WeiLi512** [comment]
Cool. I hope to see the repo soon.

**Comment by bkbooth** [comment]
I'm still not sure the best way to move this to a repo yet, I haven't been able to prioritise this. I copied what I've got into a gist in case it helps you. I'm actively implementing icon-sdk-js features into my current project so I'll be fleshing this out over the next week or 2. Feel free to add comments or revisions, we might just be able to collaborate via this gist for a bit

https://gist.github.com/bkbooth/cbb66db2057db1b81be1d7735d9031fa

At the moment I just have this local to my project in `./@types/icon-sdk-js.d.ts` and the TS compiler is finding the types definitions.

**Comment by WeiLi512** [comment]
Great
I am also using the icon-sdk-js package in my current project using typescript.
This gist will help me. I will also give feedback while using the gist in my project.
Thanks.

**Comment by bkbooth** [comment]
Setting up the gist inspired me to see what's involved in setting up the repo. I set this up and it seems to _mostly_ work, but I'm having an issue with the `bignumber.js` dependency/version in my actual project when I link this. I'll leave it for now, but feel free to take a look and see if you can get it working.

https://github.com/bkbooth/types-icon-sdk-js

**Comment by WeiLi512** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
If you knew that, you would have taken less time. I also just know that.
Anyway thanks for your work.

**Comment by bkbooth** [comment]
@WeiLi512 yeah, I found that when I first started looking around. I couldn't get it to work for `icon-sdk-js` for some reason though. Have you tried it and got it working? I might not have configured it correctly.

**Comment by WeiLi512** [comment]
It worked for me. But I had to customize it for some types.
![image](https://user-images.githubusercontent.com/50083174/114041969-961f4180-98b7-11eb-9928-02fcfcd5fbc3.png)
.

**Comment by inwonkim** [comment]
[#29 ](https://github.com/icon-project/icon-sdk-js/pull/29) We support typescript
