### ISSUE TITLE
Missing Implementation of Deposit transaction builder

### ISSUE THREAD

**Issue by ajaya-man** [icon-project/icon-sdk-js#24]
There seems to be no implementation of Deposit transaction builder. Python SDK has an incomplete implementation but here is no implementation of the deposit transaction builder. The code has been tested on iconservice.
https://github.com/icon-project/icon-service/blob/master/tests/integrate_test/test_integrate_base.py#L920

**Comment by goldworm-icon** [comment]
We have no official plan to update icon-sdk-js in the near future.
But any contributions are always welcome.

**Comment by goldworm-icon** [comment]
We discussed this issue internally and decided to update icon-sdk-js until early April.
Thank you for your feedback.

**Comment by sink772** [comment]
@ajaya-man This is for clarifying. As I said in https://github.com/icon-project/icon-sdk-python/issues/63, Python SDK has complete implementation and `term` is not a valid parameter. It's from your misunderstanding.

**Comment by ajaya-man** [comment]
@sink772 Thanks for clarifying. I got confused with the yellowpaper documentation. The documentation mentioned about different options of getting higher percentages of virtual step in the ICX deposited. So, I was wondering that how it can be done. We will work with `FIXED TERM` for now. I think we might also need to update the [yellowpaper](https://icon.foundation/resources/file/ICON_Yellowpaper_Transactionfee_EN_V1.0.pdf) with the current details.

**Comment by ajaya-man** [comment]
> We discussed this issue internally and decided to update icon-sdk-js until early April.
> Thank you for your feedback.

Thanks for taking this into consideration.

**Comment by sink772** [comment]
> I got confused with the yellowpaper documentation. The documentation mentioned about different options of getting higher percentages of virtual step in the ICX deposited. So, I was wondering that how it can be done. We will work with FIXED TERM for now. I think we might also need to update the yellowpaper with the current details.

Yes, we need to update the yellowpaper to reflect the current spec. @unamed12 @BennyOptions

**Comment by inwonkim** [comment]
@ajaya-man  You've been waiting for a long time. new version(v0.0.19) including implementation of `DepositTransactionBuilder` has released

**Comment by ajaya-man** [comment]
Thanks @inwonkim for including this.
