### ISSUE TITLE
[Question] Convert BigNumber value from getBalance method to ICX balance

### ISSUE THREAD

**Issue by duyphanz** [icon-project/icon-sdk-js#26]
Hi,

I'm using [getBalance method](https://github.com/icon-project/icon-sdk-js/blob/master/README.md#getbalance) to get balance from address `hx7c59d4c9199def4539626718ff1f4d7c8c30310b` for an example. After convert to Number, I got `2.05e+21`

My question is how to convert to the ICX balance the picture below (https://sejong.tracker.solidwallet.io/addresses) :

![image](https://user-images.githubusercontent.com/13731780/118799210-a966f900-b8c8-11eb-911a-e107d64e2caf.png)

Thanks in advance!

**Comment by ICONationDevTeam** [comment]
The result of the `getBalance` method is a BigInteger. 
That type is documented here : https://mikemcl.github.io/bignumber.js/

So if you want to convert your balance to a human readable balance like in the tracker, you need to divide the balance by 10^18 (ICX decimal precision = 18) : 

```js
import IconService, { IconConverter } from 'icon-sdk-js'

// Get balance
const httpProvider = new IconService.HttpProvider('https://ctz.solidwallet.io/api/v3');
const iconService = new IconService(httpProvider);
const balance = await iconService.getBalance('hx9d8a8376e7db9f00478feb9a46f44f0d051aab57').execute();
// Change decimal place
const balance_human = IconConverter.toBigNumber(balance).dividedBy(IconConverter.toBigNumber('10').exponentiatedBy(18));
// Prepare for display (5 decimals precision)
const result = parseFloat(balance_human.toFixed(5))
```

**Comment by ICONationDevTeam** [comment]
Alternatively, you can also use `IconAmount` :

```
const value = IconAmount.of(balance, IconAmount.Unit.LOOP).convertUnit(IconAmount.Unit.ICX).toString()
```

**Comment by duyphanz** [comment]
Thanks @ICONationDevTeam :)
