### ISSUE TITLE
No monitor block/event?

### ISSUE THREAD

**Issue by tiendq** [icon-project/icon-sdk-js#27]
When does it support monitoring functions?

e.g. `goloop rpc monitor event`

**Comment by inwonkim** [comment]
We will support the functionality of ICON2.
e.g) monitoring, icx sendTransaction And Wait..
We will implement it as soon as possible.
after implement it, I will comment on this issue.

**Comment by inwonkim** [comment]
[#63 add monitor](https://github.com/icon-project/icon-sdk-js/pull/63)
We support monitoring functions
