### ISSUE TITLE
[Question] Show to sign a transaction by ICONex wallet

### ISSUE THREAD

**Issue by duyphanz** [icon-project/icon-sdk-js#28]
Hi,

I'm trying to request signing a transaction by ICONex wallet as: https://www.icondev.io/docs/chrome-extension-connect

```
const customEvent = new CustomEvent('ICONEX_RELAY_REQUEST', detail: { 
    type: 'REQUEST_SIGNING',
    payload: {
        from: 'hx19870922...',
        hash: '0x13979...'
    }
});
```

The document mentioned that `only signing tx hash`. So, I took a look into the `icon-sdk-js` to find out how to build a transaction and get the `txHash` from it. The way I see is using `sendTransaction` method, but ONLY for `signedTransaction` which requires a Wallet instance.

```
// Returns the tx hash of transaction.
const txHash = await iconService.sendTransaction(signedTransaction).execute();
```

My questions are:

- How can I build a Wallet instance from the `privateKey` which is retrieved  `ICONex extension` if using the sendTransaction method ?
- Or, how can I get the `txHash` without using the sendTransaction method?

**Comment by ICONationDevTeam** [comment]
Hi,

Please refer to the documentation : 
https://www.icondev.io/docs/how-to-generate-a-transaction-signature

There's no available public API in the SDK that will generate that txhash, you'll have to code it yourself, or reuse the internal methods of the SDK. See here:  https://github.com/icon-project/icon-sdk-js/blob/3ab30c0dbc2759cb480942b8463044fd0c89a703/lib/data/Util.js#L77

**Comment by duyphanz** [comment]
Thanks @ICONationDevTeam :)
