### ISSUE TITLE
getLastBlock throws "[FORMAT ERROR] Confirmed transaction object is invalid."

### ISSUE THREAD

**Issue by tiendq** [icon-project/icon-sdk-js#32]
Query: `const block = await iconService.getLastBlock().execute();`

Throws error: `[FORMAT ERROR] Confirmed transaction object is invalid.`

While RPC query works well: `curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "icx_getLastBlock"}' https://btp.net.solidwallet.io/api/v3 | jq`

icon-sdk-js v1.1.0

I also found several closed issues with same this error but they happened in 2019 with old releases.

**Comment by tiendq** [comment]
Interestingly I found it only happens on our BTP testnet at `https://btp.net.solidwallet.io/api/v3` and doesn't happen on public testnet (in SDK docs) at `https://bicon.net.solidwallet.io/api/v3`.

**Comment by dhlee-icon** [comment]
ICON dev team is testing SDK js on BTP.net

**Comment by inwonkim** [comment]
@tiendq We have released fixed version(1.1.2) and it will work on btp-net

**Comment by tiendq** [comment]
> @tiendq We have released fixed version(1.1.2) and it will work on btp-net

I still got same error on btp.net

I also noticed you changed back from:

1.1.0 `const IconService = require('icon-sdk-js').default;`

to 1.1.2 `const IconService = require('icon-sdk-js');`

**Comment by tiendq** [comment]
> @tiendq We have released fixed version(1.1.2) and it will work on btp-net

Never mind, it was my mistake with a nested project.

It's fixed, no error with btp.net now.

Thank you.
