### ISSUE TITLE
getBlockByHeight returns "[RPC ERROR] NotFound : E1005:no block for 2175656"

### ISSUE THREAD

**Issue by tiendq** [icon-project/icon-sdk-js#33]
### How to test?

icon-sdk-js v1.1.2

Testnet: https://sejong.net.solidwallet.io/api/v3

`const block = await iconService.getBlockByHeight(height).execute();` with `height` = current height + 100 (any number behind head block).

### Issue

Got error message `[RPC ERROR] NotFound : E1005:no block for 2175656`

### Expectation

A nicer and clearer error message, or same with [icx_getBlockByHeight](https://www.icondev.io/references/reference-manuals/icon-json-rpc-api-v3-specification#icx_getblockbyheight) is better.

**Comment by inwonkim** [comment]
SDK returns the error message returned by rpc as it is.
The messages on the devpotal are error messages from icon1, and will be updated.

**Comment by tiendq** [comment]
> SDK returns the error message returned by rpc as it is.
> The messages on the devpotal are error messages from icon1, and will be updated.

Do you have any plan to fix it?

**Comment by inwonkim** [comment]
No, I don't have plan to customize error message.

**Comment by tiendq** [comment]
> No, I don't have plan to customize error message.

I don't think it's a customize, can you explain the structure of the message `[RPC ERROR] NotFound : E1005:no block for 2175656`? I see it isn't consistent with other RPC error messages.

**Comment by inwonkim** [comment]
As mentioned above, the sdk simply returns the rpc's response as-is.
To request update for rpc error message, open an issue in the [goloop](https://github.com/icon-project/goloop repository.)

**Comment by tiendq** [comment]
> As mentioned above, the sdk simply returns the rpc's response as-is.
> To request update for rpc error message, open an issue in the https://github.com/icon-project/goloop repository

But according to this [icx_getBlockByHeight](https://www.icondev.io/references/reference-manuals/icon-json-rpc-api-v3-specification#icx_getblockbyheight) (mentioned in the open issue), it isn't same as original RPC error.

**Comment by inwonkim** [comment]
If you run the command below, you will get an error like **[RPC ERROR] NotFound : E1005:no block for 2175656**.

`curl -X POST https://ctz.solidwallet.io/api/v3 -d '{"jsonrpc":"2.0","id":1001,"method":"icx_getBlockByHeight","params":{"height":"0x2784176"}}' -H 'Content-Type: application/json'`

**Comment by tiendq** [comment]
> If you run the command below, you will get an error like **[RPC ERROR] NotFound : E1005:no block for 2175656**.
> 
> `curl -X POST https://ctz.solidwallet.io/api/v3 -d '{"jsonrpc":"2.0","id":1001,"method":"icx_getBlockByHeight","params":{"height":"0x2784176"}}' -H 'Content-Type: application/json'`

Got it, and my other test below returned a different message (though it looks better). None of them returns error message in documentation!!!

`curl -X POST https://btp.net.solidwallet.io/api/v3 -d '{"jsonrpc":"2.0","id":1001,"method":"icx_getBlockByHeight","params":{"height":"0x3784176"}}' -H 'Content-Type: application/json'`

```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -31004,
    "message": "E1005:Not found"
  },
  "id": 1001
}
```
