### ISSUE TITLE
what is HttpProvider and how to import it

### ISSUE THREAD

**Issue by pyanishjain** [icon-project/icon-sdk-js#36]
const IconService = require("icon-sdk-js");

const httpProvider = IconService.HttpProvider("https://ctz.solidwallet.io/api/v3");
const iconService = new IconService(httpProvider);

/* Returns the total number of issued coins. */

async function main() {
  const totalSupply = await iconService.getTotalSupply().execute();
  console.log(totalSupply);
}

main();

I try this and it gives error 

const httpProvider = IconService.HttpProvider("https://ctz.solidwallet.io/api/v3");
                                 
TypeError: IconService.HttpProvider is not a function

**Comment by inwonkim** [comment]
See this [HttpProvider](https://github.com/icon-project/icon-sdk-js#iconservicehttpprovider).

And you can import HttpProvider like below
```
const IconService = require('icon-sdk-js').default;
const HttpProvider = IconService.HttpProvider;
```

**Comment by itsanishjain** [comment]
thanks this solves the issue
