### ISSUE TITLE
[RPC ERROR] SystemError: E1006:ValidateNetwork(nid=0x53) fail

### ISSUE THREAD

**Issue by itsanishjain** [icon-project/icon-sdk-js#37]
when I Try to send trasaction
`const IconService = require("icon-sdk-js").default;
const HttpProvider = IconService.HttpProvider;

const provider = new HttpProvider("https://sejong.net.solidwallet.io/api/v3");
const iconService = new IconService(provider);

async function main() {
  const transaction = new IconService.IconBuilder.IcxTransactionBuilder()
    .to("hxa67943d0586309b01d34b6297d722f3e641d8e11")
    .from("hxfcc31032b83a8edb3040ac82e9b0846969d5dd1b")
    .value(
      IconService.IconAmount.of(7, IconService.IconAmount.Unit.ICX).toLoop()
    )
    .stepLimit(IconService.IconConverter.toBigNumber(100000))
    .nid(IconService.IconConverter.toBigNumber(3))
    .nonce(IconService.IconConverter.toBigNumber(1))
    .version(IconService.IconConverter.toBigNumber(3))
    .timestamp(1544596599371000)
    .build();

  console.log(transaction);

  const wallet = IconService.IconWallet.loadPrivateKey(
    "// here I use private key of wallet which create with wallet.create method means it has NO ICX coint"
  );

  const signedTransaction = new IconService.SignedTransaction(
    transaction,
    wallet
  );
  console.log(signedTransaction.getSignature());

  // send the transaction
  try {
    const tx_hash = await iconService
      .sendTransaction(signedTransaction)
      .execute();
  } catch (err) {
    console.log("ERRROR :))))", err);
  }
}

main();
`

**Comment by ajaya-man** [comment]
Can you reformat your code and mention the issue?

**Comment by sink772** [comment]
@itsanishjain You need to specify proper NID value when you construct a transaction object. The NID of Sejong testnet is `0x53` as the error log explains.  See the below info.
https://www.icondev.io/introduction/the-icon-network/testnet#sejong

**Comment by pyanishjain** [comment]
I did that too 
it gives ERRROR :)))) [RPC ERROR] SystemError: E2002:Expired(min-455816h29m39.300911s)
that code comes from doc it self

**Comment by ajaya-man** [comment]
`.timestamp(1544596599371000)` this field should be +/- 5 minutes to the current time.

**Comment by pyanishjain** [comment]
thanks ajaya yes we need to add like this 
this works
new Date().getTime() * 1000
