### ISSUE TITLE
Wrong NID when submitting Tx 

### ISSUE THREAD

**Issue by robcxyz** [icon-project/icon-sdk-js#39]
I having issues sending transactions on mainnet with the javascript sdk. We are able to send Txs on berlin and lisbon but not on mainnet which is holding back the release of the contract verification tool.

Here you can see us building the Tx: https://github.com/geometry-labs/icon-tracker-frontend/blob/main/src/redux/store/iiss.js#L464
We are using a lookup table here: https://github.com/geometry-labs/icon-tracker-frontend/blob/main/src/redux/store/iiss.js#L395

The lookup table is how we get the nid but when we send the Tx, the nid comes out as "0xNaN" in the rpc payload which is causing the error.  We have also tried using nid=1 (int not hex) but still confused why it would work on testnet.  Any idea why on this?

Thank you for your time.

**Comment by inwonkim** [comment]
@robcxyz 
I think table is wrong.
```
const nodeId = {'https://berlin.net.solidwallet.io': '0x7',
                'https://lisbon.net.solidwallet.io': '0x2',
                'https://tracker.icon.community': '0x1'}
```
try **https://tracker.icon.community -> https://api.icon.geometry.io**

**Comment by robcxyz** [comment]
@inwonkim - That was it.  Sorry should have got that myself. My JS skill are not good...
