### ISSUE TITLE
How to detect ICONex chrome extension is installed or not ?

### ISSUE THREAD

**Issue by cloud-github** [icon-project/icon-sdk-js#4]
Trying to achieve whether ICONx chrome extension is installed in browser or not. Can anyone help me.

According to IconEx chrome extension API's documentation,

**For request :** 

````
const customEvent = new CustomEvent("ICONEX_CONNECT_REQUEST", {
      detail: {
        type: "REQUEST_HAS_ACCOUNT",
        payload: {
          jsonrpc: "2.0",
          id: 1234
        }
      }
    });
    window.dispatchEvent(customEvent);
````

**For Response:** 

````
const eventHandler = event => {
        const { type, payload } = event.detail;
        console.log("event: ", event); // should true or false . // **couldn't log event here**
        if (type === "RESPONSE_HAS_ACCOUNT") {
          console.log(payload); // true or false
        }
  };
  window.addEventListener("ICONEX_CONNECT_RESPONSE", () => eventHandler);
````

**Comment by sanghoocon** [comment]
Sorry for missing this report.
icon-sdk-js is not related to the iconex chrome extension.
But as far as I know, Even if not iconex, there is no official way to detect whether chrome extension is installed or not.
So you will have to check whether there is a response to the iconex custom event to determine installation.
