### ISSUE TITLE
Switch from XHR to Fetch for HTTP transport

### ISSUE THREAD

**Issue by rhizome-labs** [icon-project/icon-sdk-js#50]
We are trying to build a few services with the ICON JS SDK using Cloudflare Workers (edge compute). The Workers runtime only supports the Fetch API for HTTP requests. Since ICON SDK uses XHR right now, it is not compatible with Cloudflare Workers. Unfortunately we don't have the JS expertise to submit a pull request, so we wanted to see if someone on the ICON team would be able to make the change.

Reference: https://community.cloudflare.com/t/xmlhttprequest-is-not-defined/133866

**Comment by inwonkim** [comment]
@rhizome-labs Updated HttpClient to use the fetch method. try new version!

**Comment by rhizome-labs** [comment]
> @rhizome-labs Updated HttpClient to use the fetch method. try new version!

Thank you!
