### ISSUE TITLE
Example Issue

### ISSUE THREAD

**Issue by sangbeomji89** [icon-project/icon-sdk-js#53]
Hi~ I tried to use examples about 'icon-sdk-js' .

I Just did Copy & Paste
```
const httpProvider = new HttpProvider('https://ctz.solidwallet.io/api/v3');
const iconService = new IconService(httpProvider);
```
above code.

And run the code with nodejs.
But I occur "ERROR" about HttpProvider is not defined.
```
const httpProvider = new HttpProvider('https://ctz.solidwallet.io/api/v3');
                     ^

ReferenceError: HttpProvider is not defined
```
I cannot tried any more.

Plz check there issue.

**Comment by inwonkim** [comment]
Could you try this?
```javascript
import IconService from 'icon-sdk-js';
const { HttpProvider } = IconService;
const httpProvider = new HttpProvider("https://ctz.solidwallet.io/api/v3");
const iconService = new IconService(httpProvider);
```

**Comment by sangbeomji89** [comment]
> also other kind of error
> 
> /~/test-icx.js:3 const httpProvider = new HttpProvider("https://ctz.solidwallet.io/api/v3"); ^
> 
> TypeError: HttpProvider is not a constructor at Object. (/~/test-icx.js:3:22) at Module._compile (node:internal/modules/cjs/loader:1103:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) at node:internal/main/run_main_module:17:47

**Comment by ICONationDevTeam** [comment]
Have you tried the following ?

```js
import IconService from 'icon-sdk-js';

const httpProvider = new IconService.HttpProvider('https://ctz.solidwallet.io/api/v3');
const iconService = new IconService(httpProvider);
```


related issue : https://github.com/icon-project/icon-sdk-js/issues/43

**Comment by inwonkim** [comment]
@viveksharmapoudel , @sangbeomji89 From version 1.4.0, modules such as HttpProver are exported at the top level of the library. Try latest version.
