### ISSUE TITLE
Error: WebSocket is not defined trying to implement an event monitor in a nodejs app

### ISSUE THREAD

**Issue by FidelVe** [icon-project/icon-sdk-js#79]
Im trying to implement an event monitor for a contract on a nodejs application but im getting the following error:

```
Error: WebSocket is not defined
```
Looking into the source code of the sdk I can see that the `WebSocket` object (which is part of the [browsers Web API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API)) is being called here:
https://github.com/icon-project/icon-sdk-js/blob/master/lib/transport/monitor/Monitor.ts#L42

This can only work when the sdk is being used in the browser because the `WebSocket` API doesnt exists in nodejs.

I would like to confirm if it is not possible to use the sdk and implement en event monitor when coding a nodejs application.

**Comment by inwonkim** [comment]
@FidelVe Thank you for reporting the bug. I checked websocket used in [Monitor](https://github.com/icon-project/icon-sdk-js/blob/master/lib/transport/monitor/Monitor.ts) is unavailable in nodejs application. We will update Monitor to available on nodejs application as soon as possible.

**Comment by FidelVe** [comment]
thanks!

**Comment by sink772** [comment]
I think we should reopen this issue to keep track of it until it is resolved.

**Comment by sink772** [comment]
Fixed in #80
