### ISSUE TITLE
setDelegation icx_sendTransaction with delegations: [] returns error

### ISSUE THREAD

**Issue by bkbooth** [icon-project/icon-sdk-js#8]
I have a function which uses `IconBuilder.CallTransactionBuilder` to create a `setDelegation` transaction:

```js
function setDelegations(wallet, delegations) {
  const builder = new IconBuilder.CallTransactionBuilder();
  const setDelegationCall = builder
    .nid(network.nid)
    .from(wallet.getAddress())
    .to(SCORE_INSTALL_ADDRESS)
    .method('setDelegation')
    .params({ delegations: delegationsToSend })
    .stepLimit(IconConverter.toBigNumber(1000000))
    .version(API_VERSION)
    .timestamp(Date.now() * 1000)
    .build();
  const signedTransaction = new SignedTransaction(setDelegationCall, wallet);
  return iconService.sendTransaction(signedTransaction).execute();
}
```

This works fine when I pass a list of delegations, but if I pass an empty list of delegations (`.params({ delegations: [] })`), it returns an error:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32600,
    "message": "fail tx invalid signature"
  },
  "id": 1571108150709
}
```

I can achieve the desired result by passing a list of delegations with `value: 0x0` and it works, but the docs (https://www.icondev.io/docs/icon-json-rpc-v3#section-setdelegation) give an example of setting `delegations: []` for "Request to revoke all delegations", so it seems like it should work.

Is there something I'm missing or doing wrong? I'm assuming this is an issue with the JSON RPC API, not this JS library specifically. Please let me know if I should ask this question elsewhere.

**Comment by Spl3en** [comment]
> "message": "fail tx invalid signature"

That is a serialization or signature error.
It looks like it is a bug about how ICON SDK JS serializes empty arrays ?

**Comment by bkbooth** [comment]
When I looked into this a little more I started thinking the same, I started looking into the code but I'm not too familiar to debug it yet. This is what the `signedTransaction.getProperties()` looks like with:

```json
{
  "to": "cx0000000000000000000000000000000000000000",
  "from": "hxc28387c8801185231882022fe90d0b6cc8d6ac7c",
  "stepLimit": "0xf4240",
  "nid": "0x50",
  "version": "0x3",
  "timestamp": "0x594fca4613a10",
  "dataType": "call",
  "data": {
    "method": "setDelegation",
    "params": {
      "delegations": []
    }
  },
  "signature": "0icKth8hZLBTIuQqk3fSRb9tifteDeHyAH4g50L3RYcjBSoyq4X1Ro/jRsOE9HgBM1XUnzAtQIuSjtY702sCAAA="
}
```

**Comment by bkbooth** [comment]
Because of this line https://github.com/icon-project/icon-sdk-js/blob/65411d8f6240369dd2a5c23be87fdb22cebc82de/lib/data/Util.js#L116

If you pass an empty array to `arrTraverse()` it returns `']'`.

arrTraverse([]);
// "]"

**Comment by bkbooth** [comment]
I raised PR #9 which fixes the issue.

**Comment by Spl3en** [comment]
Nice catch, good job! 👍
