### ISSUE TITLE
fresh install of icon-sdk-js still creates dependency for secp256k1 v5.0.0

### ISSUE THREAD

**Issue by FidelVe** [icon-project/icon-sdk-js#95]
# Issue

A couple months ago a high security alert was raised in relation to secp256k1 on version 5.0.0, the alert title was `secp256k1-node allows private key extraction over ECDH`

`icon-sdk-js` package was updated in the following PR
https://github.com/icon-project/icon-sdk-js/commit/b4bb2f525e9c3d16e8fd437148e57f3d7c88bb09

For some reason a fresh install of `icon-sdk-js` still install the secp256k1 v5.0.0

# how to reproduce

* Create a new nodejs project with `npm init -y`
* install package by running `npm install icon-sdk-js`

check package-lock.json
```
"node_modules/secp256k1": {
      "version": "5.0.0",
      "resolved": "https://registry.npmjs.org/secp256k1/-/secp256k1-5.0.0.tgz",
      "integrity": "sha512-TKWX8xvoGHrxVdqbYeZM9w+izTF4b9z3NhSaDkdn81btvuh+ivbIMGT/zQvDtTFWhRlThpoz6LEYTr7n8A5GcA==",
      "hasInstallScript": true,
      "dependencies": {
        "elliptic": "^6.5.4",
        "node-addon-api": "^5.0.0",
        "node-gyp-build": "^4.2.0"
      },
      "engines": {
        "node": ">=14.0.0"
      }
    },
```

**Comment by sink772** [comment]
Thanks for the head up.
We need to release a new version.
I will handle this issue shortly.

**Comment by sink772** [comment]
A new version 1.5.3 has been released.
Can you please check again with the new version on your side?

**Comment by FidelVe** [comment]
Hi @sink772 

I just checked and is fixed
